version: "3.8"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    networks:
      - default
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq

networks:
  default:
    name: swsp

volumes:
  rabbitmqdata:
