apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprintapi-deployment
  labels:
    app: sprintapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sprintapi
  template:
    metadata:
      labels:
        app: sprintapi
    spec:
      containers:
        - name: sprintapi
          image: ghcr.io/miraplanner/sprint-service:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: MongoDBSettings__Username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-username  
            - name: MongoDBSettings__Password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-root-password   
            - name: MongoDBSettings__Host
              value: sprint-db
            - name: MongoDBSettings__Port
              value: "27017"
            - name: ASPNETCORE_ENVIRONMENT
              value: "Staging"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: sprintapi-service
spec:
  type: NodePort
  selector:
    app: sprintapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31010